USE mysql;
FLUSH PRIVILEGES;
DELETE FROM	mysql.user WHERE User='';
DROP DATABASE test;
DELETE FROM mysql.db WHERE Db='test';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysqlrootpwd';
CREATE DATABASE wpdatabasename CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'wpdatabaseusr'@'%' IDENTIFIED by 'wpdatabasepwd';
GRANT ALL PRIVILEGES ON wpdatabasename.* TO 'wpdatabaseusr'@'%';
FLUSH PRIVILEGES;